name: Build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - rc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4

      - name: Install Mask
        id: install-tool
        uses: jcwillox/install-tool-action@v1
        with:
          repo: "jacobdeichert/mask"
          download_url: "/releases/download/mask/0.11.4/mask-0.11.4-x86_64-unknown-linux-gnu.zip"
          bin_path: "mask-0.11.4-x86_64-unknown-linux-gnu"

      - name: Run CI
        run: mask ci

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
