name: Release
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4

      - uses: DrSensor/mask-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          commands: |-
            cd ${{ secrets.PYPI_API_TOKEN }}

  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y grep sed

      - id: version
        name: Get the version
        run: |
          tag="v$(cat kedro_partitioned/__init__.py | \
                  grep __version__ | \
                  sed "s/__version__ = '\(.*\)'/\1/")"
          echo "TAG=$tag" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.TAG }}
